openapi: 3.0.0
info:
  title: Test
  description: Test description
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /user:
    get:
      summary: Returns a list users.
      description: hi.
      responses:
        '200':
          description: A JSON array of users.
          content: 
            application/json:
              schema:
                type: array
                  items:
                    type: object
    post:
      summary: Create a new user.
      description: hi.

      requestBody:
        description: Optional.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                username:
                  type: string
                password:
                  type: string
    responses:
      '201':
        description: Created User.
        content:
          application/json:
            schema:
              type: object