openapi: 3.0.0
info:
  title: Test
  description: Test description
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /user:
    get:
      tags:
        - user
      summary: Returns a list users.
      description: hi.
      responses:
        '200':
          description: A JSON array of users.
          content: 
            application/json:
              schema:
                type: array
                  items:
                    type: object
    post:
      tags:
        - user
      summary: Create a new user.
      description: hi.

      requestBody:
        description: Optional.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Created User.
          content:
            application/json:
              schema:
                type: object
  /user/{id}:
    get:
      tags:
        - user
      summary: Returns a one user.
      parameters:
        - in: path
          name: id
          required: true
      responses:
        '200':
          description: User with  this id
          content:
            application/json:
              schema:
                type: object
    put:
      tags:
        - user
      parameters:
        - in: path
          name: id
          required: true
      requestBody:
        description: Optional.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: updated user.
          content:
            application/json:
              schema:
                type: object

    delete:
      tags:
        - user
      parameters:
        - in: path
          name: id
          required: true
      responses:
        '200':
          description: user deleted.
            content:
              application/json:
                schema:
                  type: object
  /user/signin:
    post:
      tags:
        - user
      requestBody:
          description: Optional.
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
      responses:
        '200':
          description: sign in user.
          content:
            application/json:
              schema:
                type: object
  /post:
    get:
      tags:
        - post
      summary: Returns a list posts.
      description: hi.
      responses:
        '200':
          description: A JSON array of users.
          content: 
            application/json:
              schema:
                type: array
                  items:
                    type: object
    post:
      tags:
        - post
      summary: Create a new post.
      description: hi.

      requestBody:
        description: Optional.
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                owner:
                  type: string
                image:
                  type: string
                  format: binary
      responses:
        '201':
          description: Created post.
          content:
            application/json:
              schema:
                type: object
  /post/{id}:
    get:
      tags:
        - post
      parameters:
        - in: path
          name: id
          required: true
      responses:
        '200':
          description: Post with  this id
          content:
            application/json:
              schema:
                type: object
    put:
      tags:
        - post
      parameters:
        - in: path
          name: id
          required: true
      requestBody:
        description: Optional.
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                owner:
                  type: string
                image:
                  type: string
                  format: binary
      responses:
        '200':
          description: updated post.
          content:
            application/json:
              schema:
                type: object
    delete:
      tags:
        - post
      parameters:
        - in: path
          name: id
          required: true
      responses:
        '200':
          description: user deleted.
            content:
              application/json:
                schema:
                  type: object