@baseURL = http://localhost:3000/post

### GET ALL POSTS
GET {{baseURL}}
Content-Type: application/json


### CREATE POST 
POST {{baseURL}}
Accept: application/json
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image" filename="1.png"
Content-Type: application/octet-stream
< .\my.png
--MyBoundary
Content-Dispostion: form-data; name="title"
Hello
--MyBoundary
Content-Dispostion: form-data; name="description"
Hello2
--MyBoundary
Content-Dispostion: form-data; name="title"
647baf8573ce1aa4f63f1195
--MyBoundary--



